2022-02-26 15:13:54,651 CRITICAL config_server_log.py Критическая ошибка
2022-02-26 15:13:54,651 ERROR config_server_log.py Ошибка
2022-02-26 15:13:54,651 WARNING config_server_log.py Предупреждения
2022-02-26 15:13:54,651 DEBUG config_server_log.py Отладочная информация
2022-02-26 15:13:54,651 INFO config_server_log.py Информационное сообщение
2022-02-26 15:14:40,949 CRITICAL server.py Попытка запуска сервера с неподходящим номером порта: 999. В качестве порта может быть указано число в диапазоне от 1024 до 65535
2022-02-26 15:15:14,231 CRITICAL server.py Попытка запуска сервера с неподходящим номером порта: 1024. В качестве порта может быть указано число в диапазоне от 1024 до 65535
2022-02-26 15:16:14,306 INFO server.py Запущен сервер, порт для подключений: 1025, адрес с которого принимаются подключения: 192.168.1.21 (по умолчанию соединения принимаются с любых адресов).
2022-02-26 15:18:33,194 CRITICAL server.py Попытка запуска сервера без IP-адреса для прослушивания. После параметра 'a' необходимо указать адрес, который будет слушать сервер
2022-02-26 15:18:41,938 INFO server.py Запущен сервер, порт для подключений: 1025, адрес с которого принимаются подключения:  (по умолчанию соединения принимаются с любых адресов).
2022-02-26 15:19:11,536 INFO server.py Установлено соединение с адресом и портом: ('127.0.0.1', 55970)
2022-02-26 15:19:11,536 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645877951.5362954, 'user': {'account_name': 'Guest'}}
2022-02-26 15:19:11,536 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1645877951.5362954, 'user': {'account_name': 'Guest'}}
2022-02-26 15:19:11,536 INFO server.py Cформирован и отправлен ответ {'response': 200} клиенту с адресом ('127.0.0.1', 55970)
2022-02-26 15:19:11,536 DEBUG server.py Соединение с клиентом ('127.0.0.1', 55970) закрывается.
2022-02-26 15:21:54,338 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения:  (по умолчанию соединения принимаются с любых адресов).
2022-02-26 15:22:06,688 INFO server.py Установлено соединение с адресом и портом: ('127.0.0.1', 43900)
2022-02-26 15:22:06,689 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645878126.6889575, 'user': {'account_name': 'Guest1'}}
2022-02-26 15:22:06,689 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1645878126.6889575, 'user': {'account_name': 'Guest1'}}
2022-02-26 15:22:06,689 INFO server.py Cформирован и отправлен ответ {'response': 400, 'error': 'Bad Request'} клиенту с адресом ('127.0.0.1', 43900)
2022-02-26 15:22:06,689 DEBUG server.py Соединение с клиентом ('127.0.0.1', 43900) закрывается.
2022-02-26 15:25:15,279 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения:  (по умолчанию соединения принимаются с любых адресов).
2022-02-26 15:25:19,297 INFO server.py Установлено соединение с адресом и портом: ('127.0.0.1', 43902)
2022-02-26 15:25:19,297 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645878319.2972934, 'user': {'account_name': 'Guest'}}
2022-02-26 15:25:19,297 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1645878319.2972934, 'user': {'account_name': 'Guest'}}
2022-02-26 15:25:19,297 INFO server.py Cформирован и отправлен ответ {'response': 200} клиенту с адресом ('127.0.0.1', 43902)
2022-02-26 15:25:19,297 DEBUG server.py Соединение с клиентом ('127.0.0.1', 43902) закрывается.
